--Validando el procedimiento almacenado
IF OBJECT_ID('SP_ACTUALIZARNUMEROFISCAL')IS NOT NULL
BEGIN
	DROP PROCEDURE SP_ACTUALIZARNUMEROFISCAL
END
GO
--Creando el procedimiento almacenado
CREATE PROCEDURE SP_ACTUALIZARNUMEROFISCAL(@SOPTYPE SMALLINT,@NUMFAC VARCHAR(21),@SERNUM VARCHAR(21),@MENS VARCHAR(200) OUTPUT)
AS
	BEGIN TRY		
		IF EXISTS(SELECT * FROM sop10100 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE= @SERNUM)
		BEGIN
			UPDATE sop10100 SET cstponbr = @NUMFAC WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE= @SERNUM			
			SET @MENS = 'LA FACTURA FUE ACTUALIZADA CORRECTAMENTE EN LA TABLA SOP10100: '
		END
		ELSE			
			SET @MENS = 'NO SE ENCUENTRA EN LA TABLA sop10100 LA FACTURA: '
			
		IF EXISTS(SELECT * FROM SOP30200 WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE= @SERNUM)
		BEGIN
			UPDATE SOP30200 SET cstponbr = @NUMFAC WHERE SOPTYPE = @SOPTYPE AND SOPNUMBE = @SERNUM			
			SET @MENS = 'LA FACTURA FUE ACTUALIZADA CORRECTAMENTE EN LA TABLA sop30200:'
		END
		ELSE			
			SET @MENS = @MENS + '--NO SE ENCUENTRA EN LA TABLA sop30200 LA FACTURA: '			
	END TRY
	BEGIN CATCH		
		SET @MENS = 'OCURRIO UN ERROR EN LAS MODIFICACIONES'
	END CATCH
